### ISSUE TITLE
Add a custom scrollbar in my portfolio

### ISSUE THREAD

**Issue by Starboy-Sharma** [Starboy-Sharma/portfolio#3]
- Please create a custom scrollbar and the color should be matched the theme of the portfolio.
- Your pull request must contain the screenshot of the scrollbar in my portfolio that you have developed.

**Comment by pawel975** [comment]
Hi, @Starboy-Sharma I can help you, you can assign the issue to me.

**Comment by Starboy-Sharma** [comment]
Hey @pawel975 

Please note scrollbar is already implemented the only problem is scrollbar is currently working with Chrome Browser only. Please make it available for other browsers (Firefox, Brave, Safari) too.

**Comment by Starboy-Sharma** [comment]
Hey, @pawel975 @ujwalkumar1995 has fixed this issue.

Thanks
